[build]
    base = "client/"
    command = "npm run build"
    publish = "dist/realtime-chat-app-client/"

[context.production.environment]
    NG_APP_SERVER_PROVIDER = 'heroku'

[context.deploy-preview.environment]
    NG_APP_SERVER_PROVIDER = 'railway'

[context.branch-deploy.environment]
    NG_APP_SERVER_PROVIDER = 'railway'
